spring.application.name=rotas-supermercados-api

spring.datasource.url=jdbc:mysql://localhost:3306/rotas_supermercados_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true